# Generated by Django 5.1.3 on 2024-11-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.URLField(blank=True, default='https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png', null=True),
        ),
    ]
