# Generated by Django 5.1.3 on 2024-11-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_alter_item_item_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_author",
            field=models.CharField(default="sitanshu", editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="uploaded_on",
            field=models.DateField(auto_now=True),
        ),
    ]
