# Generated by Django 5.1.3 on 2024-11-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="deafult.jpg", upload_to="profile_pictures"
            ),
        ),
    ]
